# -*- coding: utf-8 -*-
"""calculator2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158psgefReUSMRsEOwgZyp6lsy-ZxMCTy
"""

!python calculator.py

!git init
!git add calculator.py
!git commit -m "Initial scientific calculator implementation"